version: "3"

services:
  api:
    build:
      context: .
    depends_on:
      - db
    links:
      - db
    command: /bin/bash entrypoint.sh
    ports:
      - "4000:4000"
    env_file: .env

  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
